# Maintainer: MonARCH Store Contributors <maintainers@monarch.store>
pkgname=monarch-store
pkgver=0.3.0_alpha.1
pkgrel=1
pkgdesc="A premium software store for Arch Linux, powered by Tauri"
arch=('x86_64')
url="https://github.com/monarch-store/monarch-store"
license=('MIT')
depends=('webkit2gtk-4.1' 'gtk3' 'openssl' 'polkit' 'pacman-contrib' 'git')
makedepends=('cargo' 'nodejs' 'npm')
source=("git+https://github.com/monarch-store/monarch-store.git")
sha256sums=('SKIP')

prepare() {
  cd "$pkgname"
  # Install frontend dependencies
  npm install
}

build() {
  cd "$pkgname"
  # Build the application
  # We use the local tauri-cli installed via npm
  npm run tauri build
}

package() {
  cd "$pkgname"

  # 1. Install Binary
  install -Dm755 "src-tauri/target/release/monarch-store" "$pkgdir/usr/bin/monarch-store"

  # 2. Install Desktop Entry
  # Assuming standard location, if not present we create one or copy from src-tauri
  # Since we don't have a source .desktop file verified yet, I'll write one here if it doesn't exist in source, 
  # but standard Tauri setup usually bundles it. 
  # For now, let's assume we need to install the bundled one or create it.
  # Let's check if src-tauri/target/release/bundle/deb/... has it or if we should manually create.
  # Better to manually create to be safe and compliant.
  
  install -dm755 "$pkgdir/usr/share/applications"
  cat <<EOF > "$pkgdir/usr/share/applications/monarch-store.desktop"
[Desktop Entry]
Type=Application
Name=MonARCH Store
Comment=Universal Arch Linux App Manager
Exec=monarch-store
Icon=monarch-store
Categories=System;PackageManager;
Terminal=false
EOF

  # 3. Install Icons
  # Tauri generates icons in src-tauri/icons
  # We install the high-res one
  install -Dm644 "src-tauri/icons/128x128.png" "$pkgdir/usr/share/icons/hicolor/128x128/apps/monarch-store.png"
  install -Dm644 "src-tauri/icons/32x32.png" "$pkgdir/usr/share/icons/hicolor/32x32/apps/monarch-store.png"
  install -Dm644 "src-tauri/icons/icon.png" "$pkgdir/usr/share/icons/hicolor/512x512/apps/monarch-store.png"

  # 4. Install Polkit Policy
  install -Dm644 "src-tauri/com.monarch.store.policy" "$pkgdir/usr/share/polkit-1/actions/com.monarch.store.policy"
  
  # 5. Helper Script (MonARCH uses a helper script for polkit checks sometimes, verified in repair.rs)
  # repair.rs generates it dynamically, but for a package it should ideally be static.
  # The repair.rs script overrides it. 
  # compliance requirement said: "Your custom policy MUST be installed".
  # We will install the policy. The helper script is currently generated by the app (repair.rs), 
  # so we might not need to package the helper script itself if the app self-heals, 
  # BUT strict packaging prefers the helper to be owned by the package.
  # Let's install the policy as requested.
  
  # 6. License
  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
