
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSystemInfo() : Promise<Result<SystemInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkChaoticStatus() : Promise<Result<ChaoticStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_chaotic_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCacheSize() : Promise<Result<CacheSizeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOrphansWithSize() : Promise<Result<OrphansWithSizeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_orphans_with_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareChaoticComponents(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_chaotic_components", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openChaoticTerminal() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_chaotic_terminal") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prepares Flatpak for use: if the flatpak binary is missing, installs the flatpak package via pacman, then ensures the Flathub remote exists.
 * Call this when the user enables Flatpak in onboarding or Settings so they can install Flatpak apps without a separate "install flatpak" step.
 */
async prepareFlatpak(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_flatpak", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ensures the Flathub remote exists so Flatpak install/uninstall work when Flatpak is turned on (onboarding or Settings).
 * Call this when the user enables Flatpak; also run before first install (done inside install_flatpak).
 */
async ensureFlathubRemote() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_flathub_remote") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllInstalledNames() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_installed_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInfraStats() : Promise<Result<InfraStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_infra_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoCounts() : Promise<Result<{ [key in string]: string }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoStates() : Promise<Result<RepoConfig[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_states") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAurEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_aur_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleRepo(name: string, enabled: boolean, password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_repo", { name, enabled, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleRepoFamily(family: string, enabled: boolean, skipOsSync: boolean | null, password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_repo_family", { family, enabled, skipOsSync, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAurEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_aur_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isOneClickEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_one_click_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOneClickEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_one_click_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns names of required runtime binaries that are missing (git, checkupdates, pkexec).
 * Surfaces in Settings so users know why AUR or system updates may fail.
 */
async getMissingRequiredBins() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_missing_required_bins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSecurityPolicy() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_security_policy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installMonarchPolicy(password: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_monarch_policy", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async optimizeSystem(password: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_system", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerRepoSync(syncIntervalHours: number | null, password: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_repo_sync", { syncIntervalHours, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAndInstallPackage(name: string, repoName: string | null, password: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_and_install_package", { name, repoName, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAdvancedMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_advanced_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAdvancedMode(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_advanced_mode", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkAppUpdate() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_app_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isTelemetryEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_telemetry_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTelemetryEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_telemetry_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isNotificationsEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_notifications_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotificationsEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notifications_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showDesktopNotification(title: string, body: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_desktop_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstallModeCommand() : Promise<string> {
    return await TAURI_INVOKE("get_install_mode_command");
},
async isSyncOnStartupEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_sync_on_startup_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSyncOnStartupEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sync_on_startup_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns true if the pacman hook set a refresh flag (user ran pacman in terminal);
 * we clear the flag and the caller should trigger a repo sync.
 */
async checkAndClearRefreshRequested() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_and_clear_refresh_requested") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async emitSyncProgress(status: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("emit_sync_progress", { status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forceRefreshDatabases(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("force_refresh_databases", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates system pacman sync DBs (/var/lib/pacman/sync/). At launch we only run when DBs are stale (>6h) so we don't sync every open.
 * Emits to "sync-progress" so the UI can show status.
 */
async syncSystemDatabases(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_system_databases", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAutomaticHousekeepingEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_automatic_housekeeping_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutomaticHousekeepingEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_automatic_housekeeping_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async performHousekeeping(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("perform_housekeeping", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setParallelDownloads(count: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_parallel_downloads", { count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getParallelDownloads() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_parallel_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isFlatpakEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_flatpak_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFlatpakEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_flatpak_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSyncIntervalHours() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_interval_hours") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSyncIntervalHours(hours: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sync_interval_hours", { hours }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoPriorityOrder() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_priority_order") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRepoPriorityOrder(order: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_priority_order", { order }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isVerboseLogsEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_verbose_logs_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setVerboseLogsEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_verbose_logs_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isCleanBuildEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_clean_build_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCleanBuildEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clean_build_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test mirrors for a repo without changing system config. Returns top 3 with latency (ms).
 * repo_key: "arch" | "Arch" | "cachyos" | "chaotic-aur" (others fall back to arch or N/A).
 */
async testMirrors(repoKey: string) : Promise<Result<MirrorTestResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_mirrors", { repoKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns which mirror-ranking tool will be used (distro-aware). Used by Settings UI to show correct label.
 * Never runs reflector on Manjaro — rank_mirrors script uses pacman-mirrors there.
 */
async getMirrorRankTool() : Promise<string | null> {
    return await TAURI_INVOKE("get_mirror_rank_tool");
},
async rankMirrors(password: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rank_mirrors", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDistroContext() : Promise<DistroContext> {
    return await TAURI_INVOKE("get_distro_context");
},
async isOnboardingCompleted() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_onboarding_completed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnboardingCompleted(completed: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_completed", { completed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getThemeMode() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_theme_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setThemeMode(mode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_theme_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAccentColor() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accent_color") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAccentColor(color: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_accent_color", { color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHostAppearance() : Promise<Result<HostAppearance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_host_appearance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isDeclinedSystemSetup() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_declined_system_setup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeclinedSystemSetup(declined: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_declined_system_setup", { declined }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSidebarExpanded() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_sidebar_expanded") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSidebarExpanded(expanded: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sidebar_expanded", { expanded }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAlphaNoticeDismissed() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_alpha_notice_dismissed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAlphaNoticeDismissed(dismissed: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_alpha_notice_dismissed", { dismissed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSearchHistory() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_search_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSearchHistory(history: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_search_history", { history }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReadNewsIds() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_read_news_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setReadNewsIds(ids: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_read_news_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveTab() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_tab") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveTab(tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_tab", { tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSnapshotStatus() : Promise<Result<SnapshotStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snapshot_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSystemSnapshot(tool: SnapshotTool, comment: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_system_snapshot", { tool, comment }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPackages(query: string, options: SearchOptions | null) : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_packages", { query, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPackagesRich(query: string, options: SearchOptions | null) : Promise<Result<SearchResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_packages_rich", { query, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchAur(query: string) : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_aur", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPackagesByNames(names: string[], options: SearchOptions | null, cacheContext: string | null) : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_packages_by_names", { names, options, cacheContext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPackagesByCanonicalIds(ids: string[]) : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_packages_by_canonical_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChaoticPackageInfo(name: string) : Promise<Result<ChaoticPackage | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chaotic_package_info", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChaoticPackagesBatch(names: string[]) : Promise<Result<{ [key in string]: ChaoticPackage }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chaotic_packages_batch", { names }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrending(options: SearchOptions | null) : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_trending", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrendingSnapshot(options: SearchOptions | null) : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_trending_snapshot", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEssentialsSnapshot() : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_essentials_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDiscoveryHomeSnapshot() : Promise<Result<DiscoveryHomeSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_discovery_home_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPackageVariants(pkgName: string, options: SearchOptions | null) : Promise<Result<PackageVariant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_package_variants", { pkgName, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCategoryPackagesPaginated(query: CategoryQuery) : Promise<Result<PaginatedResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_category_packages_paginated", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortInstallation() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_installation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installPackage(name: string, source: PackageSource, password: string | null, repoName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_package", { name, source, password, repoName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uninstallPackage(name: string, source: PackageSource | null, password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_package", { name, source, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEssentialsList() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_essentials_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkInstalledStatus(name: string) : Promise<Result<PackageInstallStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_installed_status", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkRebootRequired() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_reboot_required") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPacnewWarnings() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pacnew_warnings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOrphans() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_orphans") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeOrphans(orphans: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_orphans", { orphans }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCacheStats() : Promise<Result<CacheStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanPackageCache(password: string | null, keepVersions: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean_package_cache", { password, keepVersions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkServicesRestart() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_services_restart") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartService(password: string | null, unit: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_service", { password, unit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPkgbuild(pkgName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_pkgbuild", { pkgName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstalledCatalog() : Promise<Result<Package[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installed_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstalledPackages() : Promise<Result<InstalledPackage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installed_packages") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdates() : Promise<Result<PendingUpdate[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFlatpakPermissions(appId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_flatpak_permissions", { appId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFullPackageDetails(name: string) : Promise<Result<FullPackageDetails, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_full_package_details", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFullPackageDetailsByCanonicalId(canonicalId: string) : Promise<Result<FullPackageDetails, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_full_package_details_by_canonical_id", { canonicalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the exact command we conceptually run for a full system upgrade.
 * Use for "Update in terminal": copy to clipboard or open user's terminal.
 * Always full -Syu (sync + upgrade) — never -Sy alone.
 */
async getSystemUpdateCommand() : Promise<SystemUpdateCommandPayload> {
    return await TAURI_INVOKE("get_system_update_command");
},
async performSystemUpdate(password: string | null, includeAur: boolean | null, includeFlatpak: boolean | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("perform_system_update", { password, includeAur, includeFlatpak }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unified Update Aggregator (Phase 2)
 * Fetches updates from Repo (including Chaotic-AUR, CachyOS, etc.), AUR, and Flatpak.
 * For updates, a source is never "turned off": we always check installed packages from every
 * source; discovery toggles (Settings → Sources) only affect search/browse, not the Updates list.
 * Repo updates come from full system pacman.conf (distro-agnostic: Arch, Manjaro, Garuda, CachyOS,
 * EOS, etc.); no filtering by app "enabled" state. Params default to true.
 */
async checkUpdates(includeAur: boolean | null, includeFlatpak: boolean | null) : Promise<Result<UpdateItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_updates", { includeAur, includeFlatpak }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUpdateSnapshot(includeAur: boolean | null, includeFlatpak: boolean | null) : Promise<Result<UpdateSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_update_snapshot", { includeAur, includeFlatpak }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unified Execution Engine (Phase 3 & 4)
 * Safely executes the update queue respecting the "Safety Lock".
 */
async applyUpdates(targets: UpdateItem[], password: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_updates", { targets, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches and normalizes news from distro-specific feeds plus Flathub.
 */
async fetchNews() : Promise<Result<NewsItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_news") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPackageIcon(pkgName: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_package_icon", { pkgName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchPackage(launchRequest: LaunchRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_package", { launchRequest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchApp(launchAppArgs: LaunchAppArgs) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_app", { launchAppArgs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearMetadataCaches() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_metadata_caches") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildMetadataIndex() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_metadata_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetadata(pkgName: string) : Promise<Result<AppMetadata | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metadata", { pkgName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetadataBatch(pkgNames: string[]) : Promise<Result<{ [key in string]: AppMetadata }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metadata_batch", { pkgNames }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkRepoSyncStatus() : Promise<Result<{ [key in string]: boolean }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_repo_sync_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyOsConfig(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_os_config", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkKeyringHealth() : Promise<Result<KeyringStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_keyring_health") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * App Store–style cancel: create cancel file so the helper exits, wait for it, then clear db lock.
 */
async cancelInstall() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_install") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async repairUnlockPacman(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_unlock_pacman", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fixKeyringIssues(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fix_keyring_issues", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async repairEmergencySync(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_emergency_sync", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkInitializationStatus() : Promise<Result<InitializationStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_initialization_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clears the sync DB health cache (in-memory and persistent file) so the next check re-probes.
 * Call this after force_refresh_databases so the UI doesn't show a stale "corrupt" banner.
 */
async clearSyncDbHealthCache() : Promise<void> {
    await TAURI_INVOKE("clear_sync_db_health_cache");
},
/**
 * Returns seconds since last sync, or None if never synced. Used to skip "sync on startup" when recently synced.
 */
async getLastSyncAgeSeconds() : Promise<string | null> {
    return await TAURI_INVOKE("get_last_sync_age_seconds");
},
async checkSystemHealth() : Promise<Result<HealthIssue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_system_health") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fixKeyringIssuesAlias(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fix_keyring_issues_alias", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async repairResetKeyring(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_reset_keyring", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkPacmanLock() : Promise<boolean> {
    return await TAURI_INVOKE("check_pacman_lock");
},
/**
 * Returns true if a stale lock exists (db.lck present and no pacman process).
 * Frontend uses this to decide whether to show the app password dialog before unlock.
 */
async needsStartupUnlock() : Promise<boolean> {
    return await TAURI_INVOKE("needs_startup_unlock");
},
/**
 * Called at app startup: if db.lck exists and no pacman process is running, remove the lock
 * so install/update/sync workflow isn't broken after a previous cancel or crash.
 * If `password` is Some (and non-empty), uses sudo path (app password box); otherwise Polkit.
 */
async unlockPacmanIfStale(password: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_pacman_if_stale", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear the pacman package cache on disk (/var/cache/pacman/pkg) via the Helper.
 * `keep`: number of versions to keep per package (0 = remove all). Helper may not yet honor this.
 */
async clearPacmanPackageCache(keep: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_pacman_package_cache", { keep }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear the native builder cache (~/.cache/monarch/build).
 */
async clearBuildCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_build_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppRating(appId: string) : Promise<Result<OdrsRating | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_rating", { appId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppRatingsBatch(appIds: string[]) : Promise<Result<{ [key in string]: OdrsRating }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_ratings_batch", { appIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppReviews(appId: string) : Promise<Result<Review[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_reviews", { appId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitReview(appId: string, rating: number, summary: string, description: string, userDisplay: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_review", { appId, rating, summary, description, userDisplay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalReviews(appId: string) : Promise<Result<LocalReview[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_reviews", { appId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trackTelemetryEvent(event: string, payload: JsonValue | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("track_telemetry_event", { event, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppMetadata = { name: string; pkg_name: string | null; icon_url: string | null; app_id: string; summary: string | null; screenshots: string[]; version: string | null; maintainer: string | null; license: string | null; last_updated: string | null; description: string | null; is_local: boolean; available_sources: PackageSource[] | null; installed: boolean | null }
/**
 * Typed response for get_cache_size (replaces raw serde_json::json!).
 */
export type CacheSizeResult = { size_bytes: string; human_readable: string }
export type CacheStats = { total_size_bytes: string; package_count: number }
export type CategoryQuery = { category: string; repo_filter: string[] | null; sort_by: string | null; page: number; limit: number; options: SearchOptions | null }
export type ChaoticMetadata = { url: string | null; desc: string | null; license: string | null; filename: string | null; buildDate: string | null }
export type ChaoticPackage = { id: string | null; pkgname: string; lastUpdated: string | null; isActive: boolean | null; version: string | null; metadata: ChaoticMetadata | null; provides: string[] | null }
/**
 * Chaotic-AUR status: compatible = host may enable (not Manjaro); chaotic_in_alpm = [chaotic-aur] in syncdbs.
 */
export type ChaoticStatus = { compatible: boolean; chaotic_in_alpm: boolean }
export type ChaoticSupport = "allowed" | "blocked" | "native"
export type DiscoveryHomeSnapshot = { essentials: Package[]; trending: Package[]; quick_starts: DiscoveryIntent[]; generated_at: string; stale: boolean }
export type DiscoveryIntent = { id: string; label: string; description: string; query: string | null; category: string | null }
export type DistroCapabilities = { repo_management: RepoManagementMode; chaotic_aur_support: ChaoticSupport; default_search_sort: string; description: string; icon_key: string }
export type DistroContext = { id: DistroId; pretty_name: string; capabilities: DistroCapabilities; cpu_tier: string; active_repos: string[] }
export type DistroId = "arch" | "manjaro" | "endeavouros" | "garuda" | "cachyos" | { unknown: string }
export type FullPackageDetails = { package: Package | null; presentation: PackagePresentation | null; installed_status: PackageInstallStatus; all_installed_variants: PackageInstallStatus[]; flatpak_permissions: string[] | null; all_variants: PackageVariant[]; display_title: string | null; primary_action: string | null; primary_action_label: string | null; selected_default_source: PackageSource | null; source_summary: string | null; security_summary: string | null; installed_source_label: string | null; source_switch_policy: string | null; source_switch_notice: string | null; security: PackageSecuritySummary | null; developer_name: string | null; donation_url: string | null }
export type HealthIssue = { category: string; severity: string; message: string; action_label: string; action_command: string | null }
export type HostAppearance = { color_scheme: string; accent_color: string | null; desktop: string }
export type InfraStats = { builders: number; users: number }
export type InitializationStatus = { needs_policy: boolean; needs_keyring: boolean; needs_migration: boolean; 
/**
 * Sync databases in /var/lib/pacman/sync/ are corrupt (Unrecognized archive format).
 */
needs_sync_db_repair: boolean; is_healthy: boolean; reasons: string[] }
export type InstalledPackage = { name: string; version: string; description: string; install_date: string | null; install_date_unix: string | null; size: string | null; size_bytes: string | null; url: string | null; repository: string | null; source_label: string | null; resolved_source: PackageSource | null; display_name: string | null; launchable: boolean; icon: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type KeyringStatus = { healthy: boolean; message: string }
export type LaunchAppArgs = { pkg_name: string }
export type LaunchRequest = { package_name: string; app_id: string | null; desktop_entry: string | null; launch_target: string | null; source: PackageSource | null }
export type LocalReview = { app_id: string; rating: number; summary: string; description: string; user_display: string; date_created: string }
/**
 * Result of testing one mirror: URL and optional latency in ms.
 */
export type MirrorTestResult = { url: string; latency_ms: number | null }
/**
 * news category for grouping in the UI.
 */
export type NewsCategory = "critical" | "system" | "discovery"
/**
 * Single news item from any distro or Flathub feed.
 */
export type NewsItem = { id: string; title: string; link: string; pub_date: string; source_label: string; is_critical: boolean; category: NewsCategory; 
/**
 * Article body/summary for inline display (from feed content or summary).
 */
content?: string | null }
export type OdrsRating = { star1: number; star2: number; star3: number; star4: number; star5: number; total: number; score: number | null }
/**
 * Typed response for get_orphans_with_size (replaces raw serde_json::json!).
 */
export type OrphansWithSizeResult = { orphans: string[]; total_size_bytes: string; human_readable: string }
export type Package = { name: string; display_name: string | null; display_title?: string | null; description: string; version: string; source: PackageSource; primary_action?: string | null; primary_action_label?: string | null; source_summary?: string | null; trust_level?: string | null; security_summary?: string | null; maintainer: string | null; license: string[] | null; url: string | null; last_modified: string | null; last_modified_unix?: string | null; first_submitted: string | null; out_of_date: string | null; keywords: string[] | null; num_votes: number | null; icon: string | null; screenshots: string[] | null; provides: string[] | null; app_id: string | null; 
/**
 * Canonical key used for merge deduplication (e.g. "discord"). Set during merge; used as React key.
 */
canonical_id?: string; is_optimized: boolean | null; depends: string[] | null; make_depends: string[] | null; is_featured: boolean | null; installed: boolean; download_size: string | null; installed_size: string | null; download_size_bytes?: string | null; installed_size_bytes?: string | null; alternatives: Package[] | null; available_sources: PackageSource[] | null; rating: OdrsRating | null; long_description: string | null; installed_sources?: string[] | null; launch_target?: string | null }
export type PackageInstallStatus = { installed: boolean; version: string | null; repo: string | null; source: PackageSource | null; actual_package_name: string | null }
export type PackagePresentation = { display_title: string | null; icon: string | null; short_description: string | null; long_description: string | null; screenshots: string[]; app_id: string | null; developer_name: string | null; donation_url: string | null }
export type PackageSecuritySummary = { trust_tier: string; system_access: string; maintainer_known: boolean; verification_note: string; user_action_note: string }
export type PackageSource = { source_type: string; id: string; version: string; label: string; package_name?: string | null }
export type PackageVariant = { source: PackageSource; version: string; repo_name: string | null; pkg_name: string | null; download_size: string | null; installed_size: string | null; maintainer: string | null; license: string[] | null; description: string | null; screenshots: string[] | null; security: PackageSecuritySummary | null }
export type PaginatedResponse = { packages: Package[]; total: number; page: number; has_more: boolean }
export type PendingUpdate = { name: string; old_version: string; new_version: string; repo: string }
export type RepoConfig = { name: string; url: string; source: PackageSource; enabled: boolean }
export type RepoManagementMode = "unlocked" | "locked" | "managed"
export type Review = { review_id: string | null; app_id: string; user_display: string | null; summary: string | null; description: string | null; rating: number | null; date_created: number | null; version: string | null; distro: string | null; locale: string | null }
export type SearchOptions = { flatpak_enabled: boolean | null; aur_enabled: boolean | null; chaotic_enabled: boolean | null; for_installed_lookup: boolean | null }
export type SearchResponse = { packages: Package[]; suggestions: SearchSuggestion[]; query_interpretation: string | null }
export type SearchSuggestion = { label: string; query: string; reason: string }
export type SnapshotStatus = { tool: SnapshotTool; is_configured: boolean; message: string }
export type SnapshotTool = "Snapper" | "Timeshift" | "None"
export type SystemInfo = { kernel: string; distro: string; pacman_version: string; chaotic_enabled: boolean; cpu_optimization: string }
/**
 * Command and label for "Update in terminal" (Apdatifier-style transparency).
 */
export type SystemUpdateCommandPayload = { command: string; description: string }
export type UpdateItem = { name: string; display_name: string | null; current_version: string; new_version: string; source: PackageSource; size: string | null; icon: string | null }
export type UpdateSnapshot = { items: UpdateSnapshotItem[]; sources: UpdateSourceStatus[] }
export type UpdateSnapshotItem = { package: Package; current_version: string; new_version: string }
export type UpdateSourceStatus = { source: string; status: string; duration_ms: string; error: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
