use tauri_specta::{collect_commands, Builder};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        // System Commands
        crate::commands::system::get_system_info,
        crate::commands::system::check_chaotic_status,
        crate::commands::system::get_cache_size,
        crate::commands::system::get_orphans_with_size,
        crate::commands::system::prepare_chaotic_components,
        crate::commands::system::open_chaotic_terminal,
        crate::commands::system::prepare_flatpak,
        crate::commands::system::ensure_flathub_remote,
        crate::commands::system::get_all_installed_names,
        crate::commands::system::get_infra_stats,
        crate::commands::system::get_repo_counts,
        crate::commands::system::get_repo_states,
        crate::commands::system::is_aur_enabled,
        crate::commands::system::toggle_repo,
        crate::commands::system::toggle_repo_family,
        crate::commands::system::set_aur_enabled,
        crate::commands::system::is_one_click_enabled,
        crate::commands::system::set_one_click_enabled,
        crate::commands::system::get_missing_required_bins,
        crate::commands::system::check_security_policy,
        crate::commands::system::install_monarch_policy,
        crate::commands::system::optimize_system,
        crate::commands::system::trigger_repo_sync,
        crate::commands::system::update_and_install_package,
        crate::commands::system::is_advanced_mode,
        crate::commands::system::set_advanced_mode,
        crate::commands::system::check_app_update,
        crate::commands::system::is_telemetry_enabled,
        crate::commands::system::set_telemetry_enabled,
        crate::commands::system::is_notifications_enabled,
        crate::commands::system::set_notifications_enabled,
        crate::commands::system::show_desktop_notification,
        crate::commands::system::get_install_mode_command,
        crate::commands::system::is_sync_on_startup_enabled,
        crate::commands::system::set_sync_on_startup_enabled,
        crate::commands::system::check_and_clear_refresh_requested,
        crate::commands::system::emit_sync_progress,
        crate::commands::system::force_refresh_databases,
        crate::commands::system::sync_system_databases,
        crate::commands::system::is_automatic_housekeeping_enabled,
        crate::commands::system::set_automatic_housekeeping_enabled,
        crate::commands::system::perform_housekeeping,
        crate::commands::system::set_parallel_downloads,
        crate::commands::system::get_parallel_downloads,
        crate::commands::system::is_flatpak_enabled,
        crate::commands::system::set_flatpak_enabled,
        crate::commands::system::get_sync_interval_hours,
        crate::commands::system::set_sync_interval_hours,
        crate::commands::system::get_repo_priority_order,
        crate::commands::system::set_repo_priority_order,
        crate::commands::system::is_verbose_logs_enabled,
        crate::commands::system::set_verbose_logs_enabled,
        crate::commands::system::is_clean_build_enabled,
        crate::commands::system::set_clean_build_enabled,
        crate::commands::system::test_mirrors,
        crate::commands::system::get_mirror_rank_tool,
        crate::commands::system::rank_mirrors,
        crate::distro_context::get_distro_context,
        crate::commands::system::is_onboarding_completed,
        crate::commands::system::set_onboarding_completed,
        crate::commands::system::get_theme_mode,
        crate::commands::system::set_theme_mode,
        crate::commands::system::get_accent_color,
        crate::commands::system::set_accent_color,
        crate::commands::system::is_declined_system_setup,
        crate::commands::system::set_declined_system_setup,
        crate::commands::system::is_sidebar_expanded,
        crate::commands::system::set_sidebar_expanded,
        crate::commands::system::is_alpha_notice_dismissed,
        crate::commands::system::set_alpha_notice_dismissed,
        crate::commands::system::get_search_history,
        crate::commands::system::set_search_history,
        crate::commands::system::get_read_news_ids,
        crate::commands::system::set_read_news_ids,
        crate::commands::system::get_active_tab,
        crate::commands::system::set_active_tab,
        crate::commands::system::get_snapshot_status,
        crate::commands::system::create_system_snapshot,
        // Search Commands
        crate::commands::search::search_packages,
        crate::commands::search::search_aur,
        crate::commands::search::get_packages_by_names,
        crate::commands::search::get_chaotic_package_info,
        crate::commands::search::get_chaotic_packages_batch,
        crate::commands::search::get_trending,
        crate::commands::search::get_package_variants,
        crate::commands::search::get_category_packages_paginated,
        // Package Commands
        crate::commands::package::abort_installation,
        crate::commands::package::install_package,
        crate::commands::package::uninstall_package,
        crate::commands::package::get_essentials_list,
        crate::commands::package::check_installed_status,
        crate::commands::package::check_reboot_required,
        crate::commands::package::get_pacnew_warnings,
        crate::commands::package::get_orphans,
        crate::commands::package::remove_orphans,
        crate::commands::package::get_cache_stats,
        crate::commands::package::clean_package_cache,
        crate::commands::package::check_services_restart,
        crate::commands::package::restart_service,
        crate::commands::package::fetch_pkgbuild,
        crate::commands::package::get_installed_packages,
        crate::commands::package::check_for_updates,
        crate::commands::package::get_flatpak_permissions,
        // Update Commands
        crate::commands::update::get_system_update_command,
        crate::commands::update::perform_system_update,
        crate::commands::update::check_updates,
        crate::commands::update::apply_updates,
        crate::commands::news::fetch_news,
        // Utils/Helpers
        crate::commands::cmd_helpers::get_package_icon,
        crate::commands::cmd_helpers::launch_app,
        crate::commands::cmd_helpers::clear_cache,
        // Metadata
        crate::metadata::get_metadata,
        crate::metadata::get_metadata_batch,
        // Repo Manager
        crate::repo_manager::check_repo_sync_status,
        crate::repo_manager::apply_os_config,
        // Repair
        crate::repair::check_keyring_health,
        crate::repair::cancel_install,
        crate::repair::repair_unlock_pacman,
        crate::repair::fix_keyring_issues,
        crate::repair::repair_emergency_sync,
        crate::repair::check_initialization_status,
        crate::repair::clear_sync_db_health_cache,
        crate::repair::get_last_sync_age_seconds,
        crate::repair::check_system_health,
        crate::repair::fix_keyring_issues_alias,
        crate::repair::repair_reset_keyring,
        crate::repair::check_pacman_lock,
        crate::repair::needs_startup_unlock,
        crate::repair::unlock_pacman_if_stale,
        crate::repair::clear_pacman_package_cache,
        crate::repair::clear_build_cache,
        // ODRS & Reviews
        crate::odrs_api::get_app_rating,
        crate::odrs_api::get_app_ratings_batch,
        crate::odrs_api::get_app_reviews,
        crate::commands::reviews::submit_review,
        crate::commands::reviews::get_local_reviews,
        crate::commands::telemetry::track_telemetry_event
    ])
}

#[test]
fn export_bindings() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap() // src-tauri
        .parent()
        .unwrap() // monarch-store
        .join("src/services/bindings.ts");

    builder()
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::String),
            path,
        )
        .expect("Failed to export bindings");
}
