// Curated list of 40 apps for Linux/Arch (fallback when backend fails). Kept in sync with docs/essentials.json and backend DEFAULT_ESSENTIALS.
// Order: Web Browsers & Communication, Office & Productivity, Graphics & Design, Multimedia & Audio, Development, Games, System
export const ESSENTIALS_POOL: string[] = [
    "firefox",
    "librewolf-bin",
    "google-chrome",
    "thunderbird",
    "telegram-desktop",
    "signal-desktop",
    "discord",
    "newsflash",
    "libreoffice-fresh",
    "obsidian",
    "calibre",
    "simplenote-electron-bin",
    "okular",
    "foliate",
    "keepassxc",
    "gimp",
    "inkscape",
    "blender",
    "flameshot",
    "krita",
    "rawtherapee",
    "vlc",
    "audacity",
    "obs-studio",
    "handbrake",
    "strawberry",
    "easyeffects",
    "ardour",
    "visual-studio-code-bin",
    "git",
    "docker-desktop",
    "steam",
    "lutris",
    "heroic-games-launcher-bin",
    "timeshift",
    "bitwarden-bin",
    "gparted",
    "kdeconnect",
    "balena-etcher",
    "peazip-bin"
];

/** Fallback IDs when get_essentials_list fails (e.g. offline). */
export const ESSENTIAL_IDS: string[] = [...ESSENTIALS_POOL];
